### ISSUE TITLE
Do this project have a specific licence?

### ISSUE THREAD

**Issue by charmyoung** [pruttned/owl-bt#13]
Hi, pruttned!
We want to use owl-bt project to generate bt structure and use it in our robotics project. So I wonder if there is a licence for this ?
And I have some advice while using it. It is not that convenient to edit the tree when the tree becomes large, as I can not use mouse to drug the tree. Maybe my interaction is wrong.
Hope to hear response from u ASAP.
Thanks!

Charles.

**Comment by pruttned** [comment]
Hi, yes. owl-bt is licensed under MIT license - basically 'do what ever you want' license.
You need to hold right mouse button to drag the tree.

**Comment by pruttned** [comment]
You mean some sort of debugger? No, currently not.

**Comment by charmyoung** [comment]
Thx！
