### ISSUE TITLE
enhancement: temp disable tree nodes

### ISSUE THREAD

**Issue by jimmymjing** [pruttned/owl-bt#18]
I think it would be great to have a feature like disabling tree node and its sub nodes. (They may get greyed out). This would be very useful for testing AI's behavior for a specific part.

**Comment by pruttned** [comment]
Hi, you are able to achieve such thing using inheritance and custom field on base node (except of greyed out part). 
E.g. something like this:
```
{
    "name": "BaseNode",
    "isAbstract" : true,
    "properties": [{
        "name": "disable",
        "type": "bool"
    } ]
},
{
    "name": "MyDerivedNode",
    "color": "blue",
    "base": "BaseNode",
}
```
