### ISSUE TITLE
Add human-readable node type to node

### ISSUE THREAD

**Issue by rubenwardy** [pruttned/owl-bt#23]
Consider allowing node types to specify a human readable name which can be different to the actual name, and used in place of the programmatic name when rendering. This will aid in translations.

```json
{
    "name": "MyNode",
    "label": "A {{ Arg }} node"
}
```

**Comment by pruttned** [comment]
This is already possible with description.
See readme:
https://github.com/pruttned/owl-bt/blob/master/readme.md#node
```
description - node description. It may contain placeholders for properties {{PropertyName}}
```
e.g.
```
"description": "Set alert level to \"{{Level}}\"",
```
is rendered like this:
![image](https://user-images.githubusercontent.com/5299952/95124932-7d8d6d80-0754-11eb-82c6-d957fb515e6c.png)
