### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by rubenwardy** [pruttned/owl-bt#25]
I installed owl-bt from npm originally, and that worked fine.

Now, I'm attempting to get a development version running so I can make some simple pull requests.

I did the following

```sh
# installed ruby, ruby-sass, and bootstrap-sass systemwide
npm install
```

I get the following error:

```
 Warning: Error: File to import not found or unreadable: bootstrap-sass/assets/stylesheets/bootstrap.
           Load paths:
             /home/user/dev/owl-bt/src/client/bower_components
             /home/user/dev/owl-bt/src/client/app
             /home/user/dev/owl-bt/src/client/components
            on line 4 of src/client/app/app.scss
```

versions:

* npm - 6.14.1
* node - 13.9.0
* ruby - 2.7
* sass - 3.7.4
* bootstrap-sass - 3.4.1

**Comment by pruttned** [comment]
Hi, you need to install bower packages.
I've added bower as a local dependency in the last commit. You are able to run it using 
```
npx bower install
```
I have also replaced grunt-contrib-sass with grunt-sass, so you don't need to have ruby installed anymore. Just remember to reinstall node modules.

**Comment by pruttned** [comment]
After that also run 
```
npm run build
```

**Comment by rubenwardy** [comment]
Cool thanks, I can confirm that works!
