### ISSUE TITLE
Update font awesome

### ISSUE THREAD

**Issue by rubenwardy** [pruttned/owl-bt#30]
Font awesome is out of date - at 4.7.0. The latest version is 5.12.1. I see that the version is limited to below 5 in the config, is this due to not having got around to fixing the breaking changes or some other reasons?

**Comment by rubenwardy** [comment]
They don't officially support bower anymore.

See https://github.com/FortAwesome/Font-Awesome/issues/11908 and https://github.com/pruttned/owl-bt/pull/31

**Comment by pruttned** [comment]
fixed in 2.0.0
