### ISSUE TITLE
Minor bug: Inverted colors for decorators and services in the Item Palette panel.

### ISSUE THREAD

**Issue by gamagan** [pruttned/owl-bt#4]
This is a minor bug. Only affects display.

On the left-hand side panel, the colors for Services and Decorators are inverted.

The services have the color blue, but they should be green. 
The decorators have the color green, but they should be blue.

When the node is placed in the workarea, the colors are displayed correctly: blue for decorators, green for services.

**Comment by pruttned** [comment]
Thanks.
Fixed in be02b61621b8b656afe3767839055619db1d0370
v1.1.3
