### ISSUE TITLE
enhancement: user-defined types

### ISSUE THREAD

**Issue by gamagan** [pruttned/owl-bt#5]
On the 1.1 addition of user-define types.

A) When a property has a user-defined type, and then you set the value of that property to a bad value, the field will turn red -- that's good. However, if you click away from the node, the value for the field is lost. Instead, the value for the field should remain, and the color should remain red. Making a mistake with the value is penalized by losing the value, which is not optimal. Keeping the value in place will make it easier to fix the error.

B) If you put a bad value on a property with a user-defined type, and then go to save the file, it will not save. That's good. However, there is no message telling you that the file was not saved. There should be a message saying that the file was not saved because of a bad property value. Ideally, the message would mention the node type and the property name, so that it's easy to locate.

**Comment by gamagan** [comment]
Any progress?

**Comment by pruttned** [comment]
Hi,
sorry I haven't had any time lately to spent on my personal projects. 
Maybe you could try to make a PR?
Thanks.

**Comment by pruttned** [comment]
a) done in 1.3.0
b) done in 1.3.0 - all invalid tree items are marked with red color and user is prompted before save if the tree is invalid

**Comment by gamagan** [comment]
Great!
